services:
  postgres:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_USER: gusmmm
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: unidade
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgsql_network
    

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gusmmm@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pgsql_network

volumes:
  postgres_data:

networks:
  pgsql_network:
    driver: bridge 